# fly.toml app configuration file generated for dashboard-ebro on 2026-04-29T10:03:14+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dashboard-ebro'
primary_region = 'cdg'

[build]

[env]
  TOKENS_FILE = "/data/tokens.json"

[[mounts]]
  source = "tokens_data"
  destination = "/data"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    soft_limit = 20
    hard_limit = 25

[[vm]]
  memory = "2gb"
  cpus = 2
  memory_mb = 2048

[checks]

  [checks.alive]
    type = "tcp"
    port = 8080
    interval = "15s"
    timeout = "10s"
    grace_period = "90s"
